POST http://localhost:8080/events
Content-Type: application/json
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MjM2Mjc0MDIsInVzZXJJZCI6MX0.xdXZRpRgk_87R5EO5CFw5ob1I_kmrPOTT-rB3uwlk_g

{
  "name": "Test event 2",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}